/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.mycompany.indagamente.Aluno;
import com.mycompany.indagamente.Usuario;
import com.mycompany.indagamente.Professor;
import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author joao vitor antoniel
 */
public class telaProfessor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaProfessor.class.getName());

    /**
     * Creates new form telaProfessor
     */
    Professor professor = new Professor();
    
    public telaProfessor(Usuario usuarioProfessor) {
         
        initComponents();
         this.professor = new Professor(
            usuarioProfessor.getIdUsuario(),
            usuarioProfessor.getUserName(),
            usuarioProfessor.getNome(),
            usuarioProfessor.getSobrenome(),
            usuarioProfessor.getSenha()
);
       
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGerarAval = new javax.swing.JButton();
        jButtonVisualizarNotas1 = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("IndagaMente");

        jButtonGerarAval.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonGerarAval.setText("Gerar Avaliação");
        jButtonGerarAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarAvalActionPerformed(evt);
            }
        });

        jButtonVisualizarNotas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVisualizarNotas1.setLabel("Visualizar Notas");
        jButtonVisualizarNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarNotas1ActionPerformed(evt);
            }
        });

        jButtonDeletar.setLabel("Deletar Conta");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(452, 452, 452))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(173, 459, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(467, 467, 467))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVisualizarNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGerarAval, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(411, 411, 411))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonSair))
                .addGap(39, 39, 39)
                .addComponent(jButtonGerarAval, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonVisualizarNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
            int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja deletar sua conta?", "Confirmar", JOptionPane.YES_NO_OPTION);
    
    if (confirmacao == JOptionPane.YES_OPTION) {
        professor.deletarConta();
        JOptionPane.showMessageDialog(this, "Conta deletada com sucesso.");
        new telaLogin().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonGerarAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarAvalActionPerformed
         telaAvaliacaoProfessor tela = new telaAvaliacaoProfessor(professor);
         tela.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonGerarAvalActionPerformed

    private void jButtonVisualizarNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarNotas1ActionPerformed
       telaBoletimProfessor telaP = new telaBoletimProfessor(professor);
       telaP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonVisualizarNotas1ActionPerformed
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Usuario usuarioFake = new Usuario(1, "user", "Joao", "Vitor", "senha123", "Professor");
        java.awt.EventQueue.invokeLater(() -> new telaProfessor(usuarioFake).setVisible(true));
    }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonGerarAval;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVisualizarNotas1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
